### PR TITLE
fix bugs for label removed.

### LINKED ISSUE #1: All tags are removed prior to the update.

### PR DESCRIPTION
**Pull request by kazuhisa**
closed #1

### CODE REVIEW

**Comment by kazuhisa** [comment]
@kazuhisa a

File: index.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ exports.handler = function(event, context) {
 
   // create tags from message.
   var create_tags_from_message = function(message){
-    var list = message.match(/@[a-z0-9_-]+/i);
```
Comment (kazuhisa) [inline index.js:41]: @test
